### ISSUE TITLE
[BUG] USSR can't find WebGL.data

### ISSUE THREAD

**Issue by crow-seeds** [kiraio-moe/USSR#4]
I used Unity 2021.3 to build the game with GZip compression. Dragging the index.html file onto the USSR.exe results in the following error:

![image](https://github.com/kiraio-moe/USSR/assets/89946108/96a07368-1ff2-4085-9211-3763712f1e6a)

Let me know if you need me to send the uncompressed WebGL.data file! I also tried it without any compression and it still has the same error.

**Comment by kiraio-moe** [comment]
> I used Unity 2021.3 to build the game with GZip compression. Dragging the index.html file onto the USSR.exe results in the following error:
> 
> ![image](https://user-images.githubusercontent.com/89946108/270080167-96a07368-1ff2-4085-9211-3763712f1e6a.png)
> 
> Let me know if you need me to send the uncompressed WebGL.data file! I also tried it without any compression and it still has the same error.

Thanks for reporting. I have checked it and yes, it's a bug.
I will work on the fixes tomorrow. Please, be patient :)

**Comment by kiraio-moe** [comment]
The codebase is a mess, so it will take time to do refactorization :(

**Comment by crow-seeds** [comment]
Yea no worries

**Comment by crow-seeds** [comment]
Yea no worries, take your time!

**Comment by crow-seeds** [comment]
Fixed it by renaming my [game name].data.gz file to WebGL.data.gz, issue is that the program specifically looks for "WebGL.data.xx"

**Comment by kiraio-moe** [comment]
> Fixed it by renaming my [game name].data.gz file to WebGL.data.gz, issue is that the program specifically looks for "WebGL.data.xx"

Yes, USSR specifically looking for `WebGL.data.*` file. If there's none, USSR won't work.
I plan to make user choose the specific file manually, so there will be no file not found errors again.

**Comment by Corjn** [comment]
Hey, I did "Fixed it by renaming my [game name].data.gz file to WebGL.data.gz, issue is that the program specifically looks for "WebGL.data.xx"" then renamed [game name].data, but still have the splashscreen. 
I'm using unity 2023.1.16
